// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

void clif_sendbgmobemblem_single(int fd, struct mob_data *md);
void clif_bg_basicinfo(struct map_session_data *sd);
void clif_bg_belonginfo(struct map_session_data *sd);
void clif_bg_memberlist(struct map_session_data *sd);
void clif_bg_positionnamelist(struct map_session_data *sd);
void clif_bg_positioninfolist(struct map_session_data *sd);
void clif_bg_skillinfo(struct map_session_data* sd);
void clif_bg_notice(struct map_session_data *sd);