// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

	int bgw_enable;
	int bgw_msg_txt;
	int bgw_mode;
	int bgw_timer_attack;
	int bgw_group_filter;
	int bgw_dual_check;
	int bgw_player_announce;
	int bgw_idle_autokick;
	int bgw_afk_timer;
	int bgw_afk_team_report;
	int bgw_afk_warp_save_point;
	int bgw_ranking_rows;
	int bgw_enable_skills;
	int bgw_name_position;
	int bgw_enable_cross_swords;
	int bgw_ignore_rate;
	int bgw_reward_rate;
	int bgw_reward_rate_min;
	int bgw_reward_rate_max;
	int bgw_reward_max_given;
	int bgw_capture_flag_path;
	int bgw_castle_defense;
