// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

	{ "queue_msg_txt",						&battle_config.queue_msg_txt, 1750, 0, INT_MAX, },
	{ "queue_max_players",					&battle_config.queue_max_players, 127, 0, INT_MAX, },
	{ "queue_dual_check",                   &battle_config.queue_dual_check, 0x00, 0x00, 0x03, },
	{ "queue_idle_autokick",                &battle_config.queue_idle_autokick, 0, 0, INT_MAX, },
	{ "queue_join_delay",                   &battle_config.queue_join_delay, 0, 0, INT_MAX, },
	{ "queue_notify",                       &battle_config.queue_notify, 0, 0, 3, },
	{ "queue_only_towns",                   &battle_config.queue_only_towns, 0, 0, 1, },
