// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

	int restock_enable;
	int restock_msg_txt;
	int restock_vip_type;
	int restock_group_level;
	int restock_regular_max_items;
	int restock_vip_max_items;
	int restock_max_stack;
	int restock_charge_oncmd;
	int restock_regular_zeny_cost;
	int restock_vip_zeny_cost;
	int restock_maps;
