// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

	int stuff_enable;
	int stuff_msg_txt;
	int stuff_bg_reserved_id;
	int stuff_gvg_reserved_id;
	int stuff_pvp_reserved_id;
	int stuff_enable_trade;
	int stuff_enable_sell;
	int stuff_enable_storage;
	int stuff_enable_guild_storage;
	int stuff_enable_drop;
	int stuff_enable_cart;