// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

	{ "stuff_enable",                       &battle_config.stuff_enable,                      1,       0,          1, },
	{ "stuff_msg_txt",                      &battle_config.stuff_msg_txt,                  1842,       0,    INT_MAX, },
	{ "stuff_bg_reserved_id",               &battle_config.stuff_bg_reserved_id,         165100,       0,    INT_MAX, },
	{ "stuff_gvg_reserved_id",              &battle_config.stuff_gvg_reserved_id,        165101,       0,    INT_MAX, },
	{ "stuff_pvp_reserved_id",              &battle_config.stuff_pvp_reserved_id,        165102,       0,    INT_MAX, },
	{ "stuff_enable_trade",                 &battle_config.stuff_enable_trade,             0x00,    0x00,       0x07, },
	{ "stuff_enable_sell",                  &battle_config.stuff_enable_sell,              0x00,    0x00,       0x07, },
    { "stuff_enable_storage",               &battle_config.stuff_enable_storage,           0x00,    0x00,       0x07, },
	{ "stuff_enable_guild_storage",         &battle_config.stuff_enable_guild_storage,     0x00,    0x00,       0x07, },
	{ "stuff_enable_drop",                  &battle_config.stuff_enable_drop,              0x00,    0x00,       0x07, },
	{ "stuff_enable_cart",                  &battle_config.stuff_enable_cart,              0x00,    0x00,       0x07, },
